name: Update package list
on:
  push:
    branches:
      - 'main'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> db
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: db
          message: Merge main into db
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Update package list
        run: python3 build_package_list.py
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package list
          branch: db
          file_pattern: package_db
